name: Build and Test
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Unit tests.
        run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: make uro